// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSpecGroup = "hmh_spec_group"

// SpecGroup mapped from table <hmh_spec_group>
type SpecGroup struct {
	ID         int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CategoryID int32     `gorm:"column:category_id;not null;comment:商品分类id" json:"category_id"` // 商品分类id
	Name       string    `gorm:"column:name;comment:规格组名称" json:"name"`                         // 规格组名称
	CreatedAt  time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName SpecGroup's table name
func (*SpecGroup) TableName() string {
	return TableNameSpecGroup
}
