// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCustomer = "hmh_customer"

// Customer mapped from table <hmh_customer>
type Customer struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Code        string         `gorm:"column:code;not null;comment:code" json:"code"`            // code
	Name        string         `gorm:"column:name;comment:姓名" json:"name"`                       // 姓名
	Account     string         `gorm:"column:account;not null;comment:账号" json:"account"`        // 账号
	Password    string         `gorm:"column:password;comment:密码" json:"password"`               // 密码
	Mobile      string         `gorm:"column:mobile;comment:手机号" json:"mobile"`                  // 手机号
	LastLoginAt time.Time      `gorm:"column:last_login_at;comment:最近登录时间" json:"last_login_at"` // 最近登录时间
	CreatedAt   time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
